# Generated by Django 5.0.1 on 2024-01-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=70, null=True)),
                ('keyword', models.CharField(blank=True, max_length=70, null=True)),
                ('desc', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(blank=True, max_length=70, null=True, upload_to='seo/images')),
                ('struct_data', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
