# Generated by Django 5.0.1 on 2024-01-29 19:11

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=70, null=True)),
                ('keywordz', models.CharField(blank=True, max_length=70, null=True)),
                ('desc', models.CharField(blank=True, max_length=150, null=True)),
                ('struct_data', models.CharField(blank=True, max_length=400, null=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=70, null=True)),
                ('keywordz', models.CharField(blank=True, max_length=70, null=True)),
                ('desc', models.CharField(blank=True, max_length=150, null=True)),
                ('struct_data', models.CharField(blank=True, max_length=400, null=True)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywordz', models.CharField(blank=True, max_length=70, null=True)),
                ('desc', models.CharField(blank=True, max_length=150, null=True)),
                ('struct_data', models.CharField(blank=True, max_length=400, null=True)),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('short_desc', models.CharField(blank=True, max_length=150, null=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images')),
                ('published', models.BooleanField(blank=True, default=False)),
                ('featured', models.BooleanField(blank=True, default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='blog.category', verbose_name='Category')),
                ('tags', models.ManyToManyField(to='blog.tag', verbose_name='tags')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
