# Generated by Django 5.0.1 on 2024-02-01 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_desc_blog_meta_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='struct_data',
            new_name='meta_struct_data',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='struct_data',
            new_name='meta_struct_data',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='struct_data',
            new_name='meta_struct_data',
        ),
    ]
