# Generated by Django 5.0.1 on 2024-02-04 11:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_struct_data_blog_meta_struct_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='meta_desc',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Meta description'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='meta_struct_data',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Structured data'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_desc',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Meta description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_struct_data',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Structured data'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='meta_desc',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Meta description'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='meta_struct_data',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Structured data'),
        ),
    ]
