# Generated by Django 5.0.1 on 2024-02-07 02:56

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=70, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=70, null=True)),
                ('meta_desc', models.CharField(blank=True, max_length=150, null=True, verbose_name='Meta description')),
                ('meta_struct_data', models.CharField(blank=True, max_length=400, null=True, verbose_name='Structured data')),
                ('meta_image', models.ImageField(blank=True, null=True, upload_to='portfolio/meta_images')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/skill_images')),
                ('progress', models.PositiveSmallIntegerField()),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, editable=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='portfolio.skillcategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('short_desc', models.CharField(blank=True, max_length=150, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images')),
                ('published', models.BooleanField(blank=True, default=False)),
                ('featured', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, editable=False)),
                ('tags', models.ManyToManyField(blank=True, related_name='projects', to='portfolio.tag', verbose_name='tags')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
